// This file was generated by counterfeiter
package fakes

import (
	"os"
	"sync"

	"github.com/cloudfoundry-incubator/ducati-cni-plugins/lib/veth"
)

type Namespace struct {
	ExecuteStub        func(func(*os.File) error) error
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 func(*os.File) error
	}
	executeReturns struct {
		result1 error
	}
	FilePathStub        func() string
	filePathMutex       sync.RWMutex
	filePathArgsForCall []struct{}
	filePathReturns     struct {
		result1 string
	}
}

func (fake *Namespace) Execute(arg1 func(*os.File) error) error {
	fake.executeMutex.Lock()
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 func(*os.File) error
	}{arg1})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(arg1)
	} else {
		return fake.executeReturns.result1
	}
}

func (fake *Namespace) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *Namespace) ExecuteArgsForCall(i int) func(*os.File) error {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].arg1
}

func (fake *Namespace) ExecuteReturns(result1 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Namespace) FilePath() string {
	fake.filePathMutex.Lock()
	fake.filePathArgsForCall = append(fake.filePathArgsForCall, struct{}{})
	fake.filePathMutex.Unlock()
	if fake.FilePathStub != nil {
		return fake.FilePathStub()
	} else {
		return fake.filePathReturns.result1
	}
}

func (fake *Namespace) FilePathCallCount() int {
	fake.filePathMutex.RLock()
	defer fake.filePathMutex.RUnlock()
	return len(fake.filePathArgsForCall)
}

func (fake *Namespace) FilePathReturns(result1 string) {
	fake.FilePathStub = nil
	fake.filePathReturns = struct {
		result1 string
	}{result1}
}

var _ veth.Namespace = new(Namespace)
