// This file was generated by counterfeiter
package fakes

import (
	"os"
	"sync"

	"github.com/cloudfoundry-incubator/ducati-cni-plugins/lib/overlay"
)

type NamespaceRepo struct {
	FindStub        func(namespacePath string) (*os.File, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		namespacePath string
	}
	findReturns struct {
		result1 *os.File
		result2 error
	}
}

func (fake *NamespaceRepo) Find(namespacePath string) (*os.File, error) {
	fake.findMutex.Lock()
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		namespacePath string
	}{namespacePath})
	fake.findMutex.Unlock()
	if fake.FindStub != nil {
		return fake.FindStub(namespacePath)
	} else {
		return fake.findReturns.result1, fake.findReturns.result2
	}
}

func (fake *NamespaceRepo) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *NamespaceRepo) FindArgsForCall(i int) string {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return fake.findArgsForCall[i].namespacePath
}

func (fake *NamespaceRepo) FindReturns(result1 *os.File, result2 error) {
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 *os.File
		result2 error
	}{result1, result2}
}

var _ overlay.NamespaceRepo = new(NamespaceRepo)
