// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-cni-plugins/lib/executor"
	"github.com/vishvananda/netlink"
)

type LinkFactory struct {
	CreateVethPairStub        func(containerID, hostIfaceName string, mtu int) (sandboxLink netlink.Link, containerLink netlink.Link, err error)
	createVethPairMutex       sync.RWMutex
	createVethPairArgsForCall []struct {
		containerID   string
		hostIfaceName string
		mtu           int
	}
	createVethPairReturns struct {
		result1 netlink.Link
		result2 netlink.Link
		result3 error
	}
}

func (fake *LinkFactory) CreateVethPair(containerID string, hostIfaceName string, mtu int) (sandboxLink netlink.Link, containerLink netlink.Link, err error) {
	fake.createVethPairMutex.Lock()
	fake.createVethPairArgsForCall = append(fake.createVethPairArgsForCall, struct {
		containerID   string
		hostIfaceName string
		mtu           int
	}{containerID, hostIfaceName, mtu})
	fake.createVethPairMutex.Unlock()
	if fake.CreateVethPairStub != nil {
		return fake.CreateVethPairStub(containerID, hostIfaceName, mtu)
	} else {
		return fake.createVethPairReturns.result1, fake.createVethPairReturns.result2, fake.createVethPairReturns.result3
	}
}

func (fake *LinkFactory) CreateVethPairCallCount() int {
	fake.createVethPairMutex.RLock()
	defer fake.createVethPairMutex.RUnlock()
	return len(fake.createVethPairArgsForCall)
}

func (fake *LinkFactory) CreateVethPairArgsForCall(i int) (string, string, int) {
	fake.createVethPairMutex.RLock()
	defer fake.createVethPairMutex.RUnlock()
	return fake.createVethPairArgsForCall[i].containerID, fake.createVethPairArgsForCall[i].hostIfaceName, fake.createVethPairArgsForCall[i].mtu
}

func (fake *LinkFactory) CreateVethPairReturns(result1 netlink.Link, result2 netlink.Link, result3 error) {
	fake.CreateVethPairStub = nil
	fake.createVethPairReturns = struct {
		result1 netlink.Link
		result2 netlink.Link
		result3 error
	}{result1, result2, result3}
}

var _ executor.LinkFactory = new(LinkFactory)
