// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-cni-plugins/lib/executor"
	"github.com/vishvananda/netns"
)

type Namespacer struct {
	GetFromPathStub        func(string) (netns.NsHandle, error)
	getFromPathMutex       sync.RWMutex
	getFromPathArgsForCall []struct {
		arg1 string
	}
	getFromPathReturns struct {
		result1 netns.NsHandle
		result2 error
	}
	SetStub        func(netns.NsHandle) error
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 netns.NsHandle
	}
	setReturns struct {
		result1 error
	}
}

func (fake *Namespacer) GetFromPath(arg1 string) (netns.NsHandle, error) {
	fake.getFromPathMutex.Lock()
	fake.getFromPathArgsForCall = append(fake.getFromPathArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.getFromPathMutex.Unlock()
	if fake.GetFromPathStub != nil {
		return fake.GetFromPathStub(arg1)
	} else {
		return fake.getFromPathReturns.result1, fake.getFromPathReturns.result2
	}
}

func (fake *Namespacer) GetFromPathCallCount() int {
	fake.getFromPathMutex.RLock()
	defer fake.getFromPathMutex.RUnlock()
	return len(fake.getFromPathArgsForCall)
}

func (fake *Namespacer) GetFromPathArgsForCall(i int) string {
	fake.getFromPathMutex.RLock()
	defer fake.getFromPathMutex.RUnlock()
	return fake.getFromPathArgsForCall[i].arg1
}

func (fake *Namespacer) GetFromPathReturns(result1 netns.NsHandle, result2 error) {
	fake.GetFromPathStub = nil
	fake.getFromPathReturns = struct {
		result1 netns.NsHandle
		result2 error
	}{result1, result2}
}

func (fake *Namespacer) Set(arg1 netns.NsHandle) error {
	fake.setMutex.Lock()
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 netns.NsHandle
	}{arg1})
	fake.setMutex.Unlock()
	if fake.SetStub != nil {
		return fake.SetStub(arg1)
	} else {
		return fake.setReturns.result1
	}
}

func (fake *Namespacer) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *Namespacer) SetArgsForCall(i int) netns.NsHandle {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return fake.setArgsForCall[i].arg1
}

func (fake *Namespacer) SetReturns(result1 error) {
	fake.SetStub = nil
	fake.setReturns = struct {
		result1 error
	}{result1}
}

var _ executor.Namespacer = new(Namespacer)
